packages:
  - '.'
  - 'landing'
  - 'app'
  - 'backend'
  - 'shared'
  - 'mobile'

allowBuilds:
  '@fails-components/webtransport-transport-http3-quiche': set this to true or false
  '@firebase/util': true
  agent-browser: set this to true or false
  esbuild: true
  node-pty: set this to true or false
  protobufjs: true
  tree-sitter: set this to true or false
  tree-sitter-javascript: set this to true or false
  tree-sitter-typescript: set this to true or false
